---
# tasks file for common
- name: Install packages with pacman
  community.general.pacman:
    name: "{{ packages }}" 
    state: present

- name: Copy the config
  ansible.builtin.copy:
    src: files/fancontrol
    dest: "/etc/fancontrol"
    owner: "root"
    mode: '777'

- name: Enable service fancontrol and ensure it is not masked
  ansible.builtin.systemd:
    name: fancontrol
    enabled: yes
    masked: no

- name: Make sure fancontrol service unit is running
  ansible.builtin.systemd:
    state: restarted
    name: fancontrol
