---
# vars file for common
driver_packages:
  - lib32-mesa
  - vulkan-radeon
  - lib32-vulkan-radeon
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - xf86-video-amdgpu
  - libva-mesa-driver
  - mesa-vdpau