---
galaxy_info:
  author: Stiven Stepanovic
  description: role to install the display manager ly
  company: your company (optional)
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: "1.2"
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: ArchLinux
  #  versions:
  #  - all
  #  - 5
  #  - 6
dependencies: []

  
