---
# tasks file for common
- name: Install packages with pacman
  community.general.pacman:
    name: "{{ packages }}" 
    state: present

- name: uncomment #unix_sock_group = "libvirt"
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '.*unix_sock_group.*'  #^#unix_sock_group
    replace: 'unix_sock_group = "libvirt"'

- name: uncomment #unix_sock_rw_perms = "0770"
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '.*unix_sock_rw_perms.*' #^#unix_sock_rw_perms
    replace: 'unix_sock_rw_perms = "0770"'

- name: Enable service libvirtd and ensure it is not masked
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    masked: no

- name: Ensure group "libvirt" exists
  group:
    name: libvirt
    state: present

- name: adding stywen to libvirt group
  ansible.builtin.user:
    name: "stywen"
    groups: "libvirt"
    append: true

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: restarted
    name: libvirtd