---
# tasks file for common
- name: Install packages with pacman
  community.general.pacman:
    name: "{{ packages }}" 
    state: present

- name: Create directory "alacritty" if it does not exist
  ansible.builtin.file:
    path: "{{home_dir}}.config/alacritty/"
    state: directory
    mode: '0755'
    owner: "{{user_name}}"

- name: Copy alacritty.yml
  ansible.builtin.copy:
    src: files/alacritty.yml
    dest: "{{home_dir}}.config/alacritty/alacritty.yml"
    owner: "{{user_name}}"
    mode: '777'

- name: change user shell to zsh 
  user:
    name: "{{user_name}}"
    shell: /bin/zsh

- name: Install oh my zsh
  become_user: "{{user_name}}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{home_dir}}.oh-my-zsh"
    depth: 1

- name: Install spaceship prompt
  become_user: "{{user_name}}"
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{home_dir}}.oh-my-zsh/custom/themes/spaceship-prompt"
    depth: 1

- name: Creating a symlink
  ansible.builtin.file:
    src: "{{home_dir}}.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{home_dir}}.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link

- name: Install zsh auto suggestion
  become_user: "{{user_name}}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{home_dir}}.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Install zsh syntax highlighting
  become_user: "{{user_name}}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{home_dir}}.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Create directory "/.local/share/fonts" if it does not exist
  ansible.builtin.file:
    path: "{{home_dir}}.local/share/fonts/"
    state: directory
    mode: '0755'
    owner: "{{user_name}}"

- name: Copy FuraMono-Regular-Powerline.otf
  ansible.builtin.copy:
    src: files/FuraMono-Regular-Powerline.otf
    dest: "{{home_dir}}.local/share/fonts/FuraMono-Regular-Powerline.otf"
    owner: "{{user_name}}"
    mode: '777'

- name: rebuild font cach
  ansible.builtin.shell: fc-cache -f -v

- name: Copy zshrc
  ansible.builtin.copy:
    src: files/zshrc
    dest: "{{home_dir}}.zshrc"
    owner: "{{user_name}}"
    mode: '777'